name: Build and Release Google Test

on:
  workflow_dispatch:
    push:
      branches: [main]
    pull_request:
    branches: [main]

jobs:
  build-and-release:
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Get latest GTest version
      id: gtest_version
      run: |
        LATEST_RELEASE=$(curl -s https://api.github.com/repos/google/googletest/releases/latest | jq -r .tag_name)
        echo "::set-output name=version::$LATEST_RELEASE"
      shell: bash

    - name: Setup CMake
      uses: lukka/get-cmake@latest

    - name: Build GTest (Unix)
      run: |
        git clone --depth 1 --branch ${{ steps.gtest_version.outputs.version }} https://github.com/google/googletest.git
        cd googletest
        mkdir build && cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON
        cmake --build . --config Release
        tar -czvf gtest-${{ steps.gtest_version.outputs.version }}-${{ runner.os }}.tar.gz lib ../googletest/include

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1

      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: gtest-${{ steps.gtest_version.outputs.version }}
        release_name: Google Test ${{ steps.gtest_version.outputs.version }}
        draft: false
        prerelease: false

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          body_path: ${{ github.workspace }}-CHANGELOG.txt
          repository: tannal/actions
          # note you'll typically need to create a personal access token
          # with permissions to create releases in the other repo
          token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}